#%RAML 1.0
title: Idempotency API
version: v1
mediaType: application/json
baseUri: hb://idempotency

types:
  IdempotencyHeader:
    enum:
      - Idempotency-Keys
  SavedResponse:
    type: object
    properties:
      response: object

/responses/{uri}/{key}:
  uriParameters:
    uri:
      description: URI of resource
    key:
      description: Idempotency key provided by client
  put:
    body: SavedResponse
    responses:
      201:
  get:
    responses:
      200:
        body: SavedResponse
