#%RAML 1.0
title: Idempotency API
version: v1
mediaType: application/json
baseUri: hb://idempotency

types:
  IdempotencyHeader:
    enum:
      - Idempotency-Key

  RequestInformation:
    type: object
    properties:
      started_at:
        type: number
        format: long
      message_id: string

/requests/{uri}/{key}:
  uriParameters:
    uri:
      description: URI of resource
    key:
      description: Idempotency key provided by client
  put:
    body:
      RequestInformation
  get:
    responses:
      200:
        body: RequestInformation

/responses/{uri}/{key}:
  uriParameters:
    uri:
      description: URI of resource
    key:
      description: Idempotency key provided by client
  put:
    responses:
      201:
      200:
  get:
    responses:
      200: